// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright (c) Protocol Labs (original checker-node.js), Prova Network contributors (modifications).
// Forked from CheckerNetwork/desktop main/checker-node.js.
//
// Spawns the Prova prover daemon (`provad`) as a child process, pipes its
// stdout/stderr into a local log buffer + activity stream, and restarts
// the process on exit. The key differences vs the upstream Checker code:
//
//   - Child is a native Go binary (`provad`), not a Node script. We use
//     `spawn` instead of `fork`; no IPC channel, just stdout/stderr pipes.
//   - Config is passed as CLI flags + environment (PROVA_KEYSTORE_PASSPHRASE)
//     rather than opaque env vars.
//   - Event format is parsed from JSON lines emitted by provad's
//     structured logger (slog with --log-format=json), not a custom
//     Station event schema.
//   - No Sentry. Log-to-disk + user-facing log view is the only telemetry.

'use strict'

const { app, dialog } = require('electron')
const { join } = require('node:path')
const { spawn } = require('node:child_process')
const wallet = require('./wallet')
const assert = require('node:assert')
const fs = require('node:fs/promises')
const consts = require('./consts')
const provaConfig = require('./prova-config')
const { randomUUID } = require('node:crypto')
const { Activities } = require('./activities')
const { Logs } = require('./logs')
const split2 = require('split2')
const { once } = require('node:events')
const { format } = require('node:util')

const log = require('electron-log').scope('provad')

/** @typedef {import('./typings').Context} Context */

// `provad` binary is bundled into the packaged app under resources/provad/.
// In dev mode we look for it next to the desktop/ directory at ../prover/provad.
const provadPath = app.isPackaged
  ? join(process.resourcesPath, 'provad', binName())
  : join(__dirname, '..', '..', 'prover', binName())

function binName () {
  return process.platform === 'win32' ? 'provad.exe' : 'provad'
}

/**
 * Write a complete prover.toml at `STATE_ROOT/prover.toml`. Covers every
 * section provad's config struct (prover/pkg/config/config.go) requires:
 *
 *   [identity]   keystore_path -> the file we just materialized
 *   [chain]      rpc_url + chain_id + contract addresses, from the
 *                user-selected network preset
 *   [storage]    data_dir -> the user-selected storage location
 *   [http]       disabled (desktop default; users wanting HTTPS retrieval
 *                run the headless prover instead)
 *   [metrics]    enabled on loopback for the dashboard
 *   [dashboard]  enabled on loopback (loop-only by default)
 *
 * The file is overwritten on every launch so any change made through
 * the UI reflects on the next supervisor restart.
 *
 * @param {string} keystorePath  Absolute path to the keystore.json that
 *   provad must decrypt with $PROVA_KEYSTORE_PASSPHRASE.
 */
async function ensureProverConfig (keystorePath) {
  const tomlPath = join(consts.STATE_ROOT, 'prover.toml')
  const dataDir = provaConfig.getStorageDir()
  const network = provaConfig.getNetworkConfig()
  await fs.mkdir(consts.STATE_ROOT, { recursive: true })
  await fs.mkdir(dataDir, { recursive: true })

  // TOML allows backslashes inside double-quoted strings only when
  // escaped, so use forward slashes everywhere. Works on Windows too.
  const fwd = (/** @type {string} */ p) => p.replace(/\\/g, '/')
  const safeDataDir = fwd(dataDir)
  const safeKeystore = fwd(keystorePath)

  const c = network.contracts
  const toml = [
    '# Auto-generated by Prova Desktop. Edits are overwritten on launch.',
    `# Network: ${network.label} (${network.key})`,
    '',
    '[identity]',
    `keystore_path = "${safeKeystore}"`,
    '# Passphrase is supplied via $PROVA_KEYSTORE_PASSPHRASE at runtime.',
    '',
    '[chain]',
    `rpc_url = "${network.rpcUrl}"`,
    `chain_id = ${network.chainId}`,
    'poll_interval_seconds = 12',
    '',
    '[chain.contracts]',
    `prova_token = "${c.provaToken}"`,
    `proof_verifier = "${c.proofVerifier}"`,
    `prover_registry = "${c.proverRegistry}"`,
    `prover_staking = "${c.proverStaking}"`,
    `content_registry = "${c.contentRegistry}"`,
    `storage_marketplace = "${c.storageMarketplace}"`,
    '',
    '[storage]',
    `data_dir = "${safeDataDir}"`,
    '',
    '[http]',
    'enabled = false',
    '',
    '[metrics]',
    'enabled = true',
    'listen_addr = "127.0.0.1:9095"',
    '',
    '[dashboard]',
    'enabled = false',
    'listen_addr = "127.0.0.1:9096"',
    ''
  ].join('\n')

  await fs.writeFile(tomlPath, toml, 'utf8')
  log.info(format('wrote prover.toml: network=%s data_dir=%s', network.key, safeDataDir))
}

log.info(format('provad binary: %s', provadPath))

const logs = new Logs()
const activities = new Activities()
let totalProofsSubmitted = 0
let totalDealsActive = 0

/**
 * @param {Context} ctx
 */
async function setup (ctx) {
  ctx.saveModuleLogsAs = async () => {
    const opts = {
      defaultPath: `prova-logs-${(new Date()).getTime()}.log`
    }
    ctx.showUI()
    const { filePath } = await dialog.showSaveDialog(opts)
    if (filePath) {
      await fs.writeFile(filePath, logs.get())
    }
  }
}

/**
 * Supervisor loop: keep provad running. If it exits (crash, RPC blip,
 * forced restart), relaunch after a short backoff. Single-instance only;
 * we don't run multiple provad processes per desktop.
 *
 * @param {Context} ctx
 */
async function run (ctx) {
  // Test hook: e2e tests boot the app without a real provad binary.
  // We want the UI to come up (wallet, dashboard, settings) without the
  // supervisor trying and failing to spawn. ENOENT would spam the logs.
  if (process.env.PROVA_DISABLE_DAEMON === '1') {
    log.info('PROVA_DISABLE_DAEMON=1 set; daemon supervisor disabled')
    return new Promise(() => {}) // never resolves; caller expects run() to block
  }

  let backoffMs = 1000
  const backoffMax = 30_000
  let consecutiveFailures = 0

  while (true) {
    /** @type {{ ok: boolean, exitCode: number | null, message: string, attempt: number, backoffMs: number }} */
    let report = { ok: true, exitCode: 0, message: '', attempt: consecutiveFailures, backoffMs }
    try {
      await start(ctx)
      backoffMs = 1000 // reset on clean exit
      consecutiveFailures = 0
      report = { ok: true, exitCode: 0, message: 'provad exited cleanly', attempt: 0, backoffMs }
      daemonStatus = { state: 'running', lastError: '', lastExitCode: 0, consecutiveFailures: 0 }
    } catch (/** @type {unknown} */ err) {
      consecutiveFailures += 1
      const msg = err instanceof Error ? err.message : String(err)
      log.error(format('provad start failed:', err))
      logs.pushLine(`[supervisor] ${msg}`)
      // Heuristic: pluck the trailing exit code from start()'s thrown
      // 'wallet authentication failed' (exit 2) and similar diagnostic
      // messages. -1 means we never got an exit code (e.g., binary
      // missing).
      const exitMatch = /exit code (\d+)/i.exec(msg)
      const exitCode = exitMatch ? Number(exitMatch[1]) : null
      report = { ok: false, exitCode, message: msg, attempt: consecutiveFailures, backoffMs }
      daemonStatus = {
        state: 'failing',
        lastError: msg,
        lastExitCode: exitCode,
        consecutiveFailures
      }
    }
    notifyDaemonStatusChanged()
    // Small delay before restart so we don't hammer on repeated config errors
    await new Promise(r => setTimeout(r, backoffMs))
    backoffMs = Math.min(backoffMax, backoffMs * 2)
  }
}

// ── daemon status surface for the renderer ────────────────────────────────────────────
//
// We surface a coarse-grained status snapshot so the UI can show a
// banner like 'Prover daemon failed to start (exit 2 — wallet auth)'
// instead of failing silently. The supervisor mutates `daemonStatus`
// on every state transition; the IPC handler in main/ipc.js reads
// it on demand, and the supervisor fires `prova:daemon-status-changed`
// after each transition for push-based subscribers.

/**
 * @typedef {{
 *   state: 'idle' | 'starting' | 'running' | 'failing',
 *   lastError: string,
 *   lastExitCode: number | null,
 *   consecutiveFailures: number
 * }} DaemonStatus
 */

/** @type {DaemonStatus} */
let daemonStatus = {
  state: 'idle',
  lastError: '',
  lastExitCode: null,
  consecutiveFailures: 0
}

function getDaemonStatus () {
  return { ...daemonStatus }
}

function notifyDaemonStatusChanged () {
  // Lazy require to avoid a circular dependency between provad.js and ipc.js.
  try {
    const { ipcMain } = require('electron')
    const { ipcMainEvents } = require('./ipc')
    ipcMain.emit(ipcMainEvents.DAEMON_STATUS_CHANGED, getDaemonStatus())
  } catch (/** @type {unknown} */ err) {
    // ipcMain is unavailable during very early boot; ignore.
  }
}

/**
 * @param {Context} ctx
 */
async function start (ctx) {
  log.info('Starting provad...')
  daemonStatus = {
    state: 'starting',
    lastError: daemonStatus.lastError,
    lastExitCode: daemonStatus.lastExitCode,
    consecutiveFailures: daemonStatus.consecutiveFailures
  }
  notifyDaemonStatusChanged()

  // Verify binary exists before attempting spawn. Gives a clearer error
  // than the generic ENOENT from child_process.
  try {
    await fs.access(provadPath, fs.constants.X_OK)
  } catch (err) {
    throw new Error(
      `provad binary not found or not executable at ${provadPath}. ` +
      'In development, build it with `cd prover && go build -o provad ./cmd/provad`.'
    )
  }

  await wallet.getAddress() // assert wallet is initialized before keystore write
  const passphrase = await wallet.getKeystorePassphrase()

  // Materialize the geth-format keystore on first boot. Idempotent —
  // skips if the file is already there.
  const keystorePath = join(consts.STATE_ROOT, 'keystore.json')
  await fs.mkdir(consts.STATE_ROOT, { recursive: true })
  const ks = await wallet.ensureKeystoreFile(keystorePath)
  if (ks.created) log.info(format('keystore created at %s', ks.path))

  // Write a fresh prover.toml every boot so user-driven config changes
  // (storage location, network selection) take effect on the next
  // supervisor restart without a manual file edit.
  await ensureProverConfig(keystorePath)

  const childProcess = spawn(
    provadPath,
    [
      '--config', join(consts.STATE_ROOT, 'prover.toml'),
      '--log-format', 'json',
      'start'
    ],
    {
      env: {
        ...process.env,
        PROVA_KEYSTORE_PASSPHRASE: passphrase
      },
      stdio: ['ignore', 'pipe', 'pipe']
    }
  )
  log.info(format('provad pid: %d', childProcess.pid))

  assert(childProcess.stdout)
  childProcess.stdout.setEncoding('utf8')
  childProcess.stdout
    .pipe(split2())
    .on('data', line => {
      logs.pushLine(line)
      parseStdoutLine(ctx, line)
    })

  assert(childProcess.stderr)
  childProcess.stderr.setEncoding('utf8')
  childProcess.stderr
    .pipe(split2())
    .on('data', line => logs.pushLine(`[stderr] ${line}`))

  // Ensure we kill the child if the app quits.
  const onBeforeQuit = () => {
    log.info('before-quit: sending SIGTERM to provad')
    childProcess.kill('SIGTERM')
  }
  app.on('before-quit', onBeforeQuit)

  const onceExited = once(childProcess, 'exit')
  const onceClosed = once(childProcess, 'close')

  const [exitCode, exitSignal] = await onceExited
  app.removeListener('before-quit', onBeforeQuit)
  const reason = exitSignal
    ? `via signal ${exitSignal}`
    : `with code ${exitCode}`
  log.info(`provad exited ${reason}`)

  const [closeCode] = await onceClosed
  log.info(`provad closed all stdio with code ${closeCode ?? '<no code>'}`)

  // Exit code semantics for provad (documented in prover/cmd/provad/main.go):
  //   0 = clean shutdown (SIGTERM, graceful drain)
  //   1 = generic error (bad config, RPC unreachable at start)
  //   2 = wallet authentication failed (bad passphrase / missing keystore)
  if (closeCode === 2) {
    throw new Error(
      'provad: wallet authentication failed (exit code 2). Check the passphrase stored in the OS keychain.'
    )
  }
  if (typeof closeCode === 'number' && closeCode !== 0) {
    throw new Error(`provad: exited with non-zero exit code ${closeCode}`)
  }
}

/**
 * Parse a single JSON log line from provad and translate it into UI activity
 * or metric updates.
 *
 * provad emits slog JSON like:
 *   {"time":"2026-04-24T18:00:00Z","level":"INFO","msg":"deal accepted","dealID":42,...}
 *
 * We recognise a handful of high-signal messages and route them to the UI;
 * everything else just goes into the log buffer for the "Logs" view.
 *
 * @param {Context} ctx
 * @param {string} line
 */
function parseStdoutLine (ctx, line) {
  let ev
  try {
    ev = JSON.parse(line)
  } catch {
    return // non-JSON lines (boot banner, etc) are fine to ignore here
  }

  const msg = ev.msg || ''

  // Provad emits its slog messages from a handful of subsystems. We map
  // the message strings we actually want surfaced into typed activity
  // rows, and mirror provad's subsystem name as the activity `source`
  // so activities.js's ONLINE_SOURCES check sees a hit and the tray
  // icon flips to the on state.
  //
  // The full list of msgs provad emits is grep-able in:
  //   prover/cmd/provad/main.go      ('provad start', 'on-chain accepter wired')
  //   prover/pkg/daemon/daemon.go    ('daemon starting', 'new deals ingested',
  //                                   'poll complete', 'shutdown signal received',
  //                                   'fatal error from loop', 'tick failed', ...)
  //   prover/pkg/deal/engine.go      ('deal ingested', 'deal step failed')
  //   prover/pkg/deal/events.go      ('source url resolution failed',
  //                                   'ingest deal failed', 'mark active failed')
  //   prover/pkg/httpserver/server.go ('http server starting',
  //                                   'http server shutting down', 'http')
  //
  // If you add a new high-signal msg in the prover, mirror it here.
  switch (msg) {
    // ── lifecycle (boot/shutdown) ────────────────────────────────────────────────────
    case 'provad start':
      activities.push(ctx, {
        type: 'started',
        source: 'provad',
        message: `provad started${ev.network ? ` (${ev.network})` : ''}`,
        timestamp: new Date(),
        id: randomUUID()
      })
      break
    case 'daemon starting':
      activities.push(ctx, {
        type: 'started',
        source: 'daemon',
        message: 'daemon starting',
        timestamp: new Date(),
        id: randomUUID()
      })
      break
    case 'on-chain accepter wired':
      activities.push(ctx, {
        type: 'info',
        source: 'daemon',
        message: `on-chain accepter wired (${ev.proofVerifier || 'verifier'})`,
        timestamp: new Date(),
        id: randomUUID()
      })
      break
    case 'shutdown signal received':
    case 'daemon stopped cleanly':
      activities.push(ctx, {
        type: 'info',
        source: 'daemon',
        message: msg,
        timestamp: new Date(),
        id: randomUUID()
      })
      break
    case 'fatal error from loop':
    case 'shutdown timeout exceeded, exiting with outstanding goroutines':
      activities.push(ctx, {
        type: 'error',
        source: 'daemon',
        message: `${msg}${ev.err ? `: ${ev.err}` : ''}`,
        timestamp: new Date(),
        id: randomUUID()
      })
      break

    // ── deal pipeline ─────────────────────────────────────────────────────────────────
    case 'deal ingested': {
      // Each new deal increments the active counter. The counter is
      // best-effort; the daemon doesn't currently emit decrements when
      // deals complete or fault, so it converges to ground truth on
      // every restart rather than every event.
      totalDealsActive += 1
      if (typeof ctx.setTotalDealsActive === 'function') {
        ctx.setTotalDealsActive(totalDealsActive)
      }
      activities.push(ctx, {
        type: 'info',
        source: 'engine',
        message: `Deal #${ev.dealID || ev.deal_id || '?'} ingested${
          ev.size ? ` (${formatBytes(Number(ev.size))})` : ''
        }`,
        timestamp: new Date(),
        id: randomUUID()
      })
      break
    }
    case 'new deals ingested':
      activities.push(ctx, {
        type: 'info',
        source: 'daemon',
        message: `${ev.count || 0} new deal${ev.count === 1 ? '' : 's'} ingested at block ${ev.currentBlock || '?'}`,
        timestamp: new Date(),
        id: randomUUID()
      })
      break
    case 'deal step failed':
    case 'ingest deal failed':
    case 'mark active failed':
    case 'source url resolution failed':
      activities.push(ctx, {
        type: 'error',
        source: 'engine',
        message: `${msg}${ev.err ? `: ${ev.err}` : ''}`,
        timestamp: new Date(),
        id: randomUUID()
      })
      break
    case 'poll complete':
      // Heartbeat; intentionally not surfaced as activity. We use it as
      // a side-effect signal that the prover is still polling.
      activities.push(ctx, {
        type: 'info',
        source: 'daemon',
        message: `poll complete${ev.height ? ` @ ${ev.height}` : ''}`,
        timestamp: new Date(),
        id: randomUUID()
      })
      break

    // ── HTTP retrieval ───────────────────────────────────────────────────────────────
    case 'http server starting':
      activities.push(ctx, {
        type: 'started',
        source: 'httpserver',
        message: `HTTP retrieval server listening on ${ev.addr || '?'}`,
        timestamp: new Date(),
        id: randomUUID()
      })
      break
    case 'http server shutting down':
      activities.push(ctx, {
        type: 'info',
        source: 'httpserver',
        message: 'HTTP retrieval server shutting down',
        timestamp: new Date(),
        id: randomUUID()
      })
      break

    // ── PDP proof events (forward-compatible ─ daemon doesn't emit these yet) ────────
    case 'proof submitted':
      totalProofsSubmitted += 1
      if (typeof ctx.setTotalProofsSubmitted === 'function') {
        ctx.setTotalProofsSubmitted(totalProofsSubmitted)
      }
      activities.push(ctx, {
        type: 'info',
        source: 'pdp',
        message: `Proof submitted for deal #${ev.dealID} (epoch ${ev.epoch})`,
        timestamp: new Date(),
        id: randomUUID()
      })
      break
    case 'proof failed':
      activities.push(ctx, {
        type: 'error',
        source: 'pdp',
        message: `Proof failed for deal #${ev.dealID}: ${ev.err || ev.error || 'unknown'}`,
        timestamp: new Date(),
        id: randomUUID()
      })
      break

    // ── catch-all for ERROR-level lines we didn't explicitly model ───────────────
    default:
      if (ev.level === 'ERROR') {
        activities.push(ctx, {
          type: 'error',
          source: 'provad',
          message: msg + (ev.err ? `: ${ev.err}` : ''),
          timestamp: new Date(),
          id: randomUUID()
        })
      }
  }
}

/** @param {number} n */
function formatBytes (n) {
  if (!Number.isFinite(n) || n <= 0) return '0 B'
  const units = ['B', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB']
  let i = 0
  let x = n
  while (x >= 1024 && i < units.length - 1) {
    x /= 1024
    i++
  }
  return `${x.toFixed(x >= 100 ? 0 : 1)} ${units[i]}`
}

module.exports = {
  setup,
  run,
  isOnline: () => activities.isOnline(),
  getActivities: () => activities.get(),
  getTotalProofsSubmitted: () => totalProofsSubmitted,
  getTotalDealsActive: () => totalDealsActive,
  getDaemonStatus
}
